### ISSUE TITLE
All images metadata stored in mongo defaults to ext4 format

### ISSUE THREAD

**Issue by dmjacobsen** [NERSC/shifter#105]
This means that image expiry doesn't actually delete the image file (it tries to delete <image>.ext4, instead of <image>.squashfs

I also saw that the list of admins was being handled as a string instead of a json list?  Any reason for that?  I converted it to a json list, we can back that out if you have reasons for doing otherwise.

See the "adminList" branch in PR 104.

-Doug

**Comment by scanon** [comment]
I'm pretty sure this was fixed.
