### ISSUE TITLE
please update Dockerfile for recent improvements

### ISSUE THREAD

**Issue by dmjacobsen** [NERSC/shifter#111]
in particular the imagegw.py script should be avoided and gunicorn used for the api, e.g.,

/usr/bin/gunicorn -b 0.0.0.0:5000 --backlog 2048 --access-logfile=/var/log/shifter_imagegw/access.log --log-file=/var/log/shifter_imagegw/error.log shifter_imagegw.api:app

for the worker, need to set PYTHONPATH to include the sitecustomize.py to get celery to properly do unicode.

**Comment by scanon** [comment]
Done.
