### ISSUE TITLE
Make slack channel public

### ISSUE THREAD

**Issue by TMiguelT** [NERSC/shifter#133]
The documentation links to the slack channel: https://shifter-hpc.slack.com/

However this is only accessible for people with @lbl.gov accounts. Can the channel be made public or the discussion moved to a [gitter](https://gitter.im) channel instead?

**Comment by dmjacobsen** [comment]
the slack channel is for developers by invitation.  Unfortunately I don't think at the slack level we're at we can make it "public".  However, I like your suggestion about trying gitter for general discussion.

I've set one up at https://gitter.im/NERSC/shifter
