### ISSUE TITLE
imagegw ignores port number for non-standard registry

### ISSUE THREAD

**Issue by chrissamuel** [NERSC/shifter#134]
Hi there,

When defining a non-standard registry thus:

"server": "f.q.d.n:1234",

the imagegw code does:

        if ':' in server:
            (server, port) = server.split(':')
        if protocol == 'http':
            conn = httplib.HTTPConnection(server)

so it pulls out the server and the port number, but then ignores the port number when making a connection (port is also ignored in the https connection as well from what I see).

I think that's simple to fix by doing this instead:

            conn = httplib.HTTPConnection(server, port)

(and presumably the analagous version for the https variant)

cheers!
Chris

**Comment by dmjacobsen** [comment]
We'll check into that, thanks for pointing it out!
