### ISSUE TITLE
Feature request: command line flag to honour Docker containers home/working directory

### ISSUE THREAD

**Issue by chrissamuel** [NERSC/shifter#135]
Hi folks,

The folks who drove our production deployment have a container that relies on the home/working directory that is set by the original Docker container, not the home directory that they have on the cluster.

Would it be possible to add support for the `Docker run -w/--workdir` options to set a working directory at Shifter run time please?

thanks,
Chris

**Comment by lijiang2014** [comment]
Hi @chrissamuel  ，
   I think you can try to set the "siteFs" in the udiRoot.conf .
   When I set :  

`siteFs = /HOME:/HOME`
I can use my home directory /HOME/username. which is set in /etc/passwd

but I want the siteFs can support more than one mount pair , as the pair WORK:WORK is also need for me.

**Comment by chrissamuel** [comment]
Hi @lijiang2014, we've had that set up from day 1, but that's not what they want at all.

Their software expects to be run from a directory under /opt, their docker container has no knowledge of the filesystems here so siteFS doesn't help them other than specifying an an area of the filesystem containing directories that they can then mount into the container via the `--volume` option to `shifter`.

Hope that helps!

All the best,
Chris

**Comment by dmjacobsen** [comment]
Yes, we're planning on adding workdir, environment overrides, and proper entry point support in the next major update.

**Comment by dmjacobsen** [comment]
@lijiang2014, you can have multiple siteFs mounts, they just need to be semicolon formatted, like:

`siteFs=/home:/home;/scratch:/scratch`

Just make sure not override anything under paths like /usr as any path specified in siteFs will block out user content anywhere along the path in the current version (future versions using overlayfs will probably be more permissive in this regard).

-Doug

**Comment by lijiang2014** [comment]
@dmjacobsen . Thanks , it works !

**Comment by scanon** [comment]
I've added support for the working directory in the latest versions.  I'm going to close this out.

**Comment by chrissamuel** [comment]
On 26/03/18 05:09, Shane Canon wrote:

> I've added support for the working directory in the latest versions. I'm 
> going to close this out.

Thanks Shane!

-- 
  Chris Samuel  :  http://www.csamuel.org/  :  Melbourne, VIC
