### ISSUE TITLE
Binding a directory from the host OS

### ISSUE THREAD

**Issue by ashkarin** [NERSC/shifter#144]
Hello,

I have an issue with binding a directory from the host OS into the container.
The directory is mounted using NFS4.
`nfs4 defaults,minorversion=1,rw,exec,_netdev,nofail,soft,nodiratime,noatime,noauto 0 0`

I execute:
`shifter --volume=/home/username/my_dir:/mnt --image=IMG`
and get into the container. But the /mnt directory is empty.

Also, when I tried to mount the directory with the path: /mnt/my_other_dir ,
I got the error:
`FAILED to find volume "from": /var/udiMount//mnt/my_other_dir`

Is it possible to bind such directories?

Thanks,
Andrei

**Comment by dmjacobsen** [comment]
Hello,

I'm guessing that `/home` is not being made available by the administrator in the udiRoot.conf `siteFs` variable.  User requestable volume mounts only allow bind mounts within the container environment, they do not allow users to import content from the external environment.

Try adding, `siteFs=/home:/home` to your udiRoot.conf and I bet it starts working.
-Doug

**Comment by ashkarin** [comment]
Thanks, Doug . The issue was resolved.  :+1:

Best regards,
Andrei
