### ISSUE TITLE
shifter usage misleading regarding --volume option

### ISSUE THREAD

**Issue by alanm-cray** [NERSC/shifter#146]
The usage/help for the shifter command gives this as the command usage:

[[USAGE]]
Usage:
shifter [-h|--help] [-v|--verbose] [--image=<imageType>:<imageTag>]
    [--entry] [-V|--volume=/path/to/bind:/mnt/in/image[:<flags>][,...]]
    [-- /command/to/exec/in/shifter [args...]]
...
[[/USAGE]]

Based on this, I would assume that one could specify additional volume mappings by separating them with a ',' character.  However, this is not the case; multiple volume mappings should either be separated from each other with a ';' character, or by using multiple '--volume' options.  The ',' is meant to separate multiple flag settings for a given volume mapping.

So for example, the correct way to specify mapping '/vol1:/newvol1' and '/vol2:/newvol2', with 'flag1' and 'flag2' applied to the latter mapping would be:
[[CORRECT_EXAMPLE_1]]
... --volume=/vol1:/newvol1\;/vol2:/newvol2:flag1,flag2 ...
[[/CORRECT_EXAMPLE_1]]

or
[[CORRECT_EXAMPLE_2]]
... --volume=/vol1:/newvol1 --volume=/vol2:/newvol2:flag1,flag2 ...
[[/CORRECT_EXAMPLE_2]]

The volume usage should probably look something like this:
[-V|--volume=/path/to/bind:/mnt/in/image[:<flags>[,...]][;...]]

**Comment by dmjacobsen** [comment]
This is now fixed.
