### ISSUE TITLE
Set container related environment variables

### ISSUE THREAD

**Issue by scanon** [NERSC/shifter#150]
Via email thread on Shifter-hpc

It would be tremendously useful to expose the name of the container as an environment variable within a container, even if it is not set in the global namespace. This could use the existing SHIFTER_* variables.

For example, 
    
     centos7% echo $SHIFTER $SHIFTER_IMAGETYPE $SHIFTER_IMAGE $SHIFTER_RUNTIME
     centos7%
     centos7% env | grep SHIFTER
     centos7%
     centos7% shifter --image=docker:ubuntu/15.04 env | grep SHIFTER
     SHIFTER=docker:ubuntu/15.04
     SHIFTER_IMAGETYPE=docker
     SHIFTER_IMAGE=ubuntu/15.04
     SHIFTER_RUNTIME=1
     centos7%

Thanks,

Mark

**Comment by dmjacobsen** [comment]
SHIFTER_IMAGEREQUEST will have the exact string requested by the user, e.g., `ubuntu:latest` or `docker:ubuntu:latest` or `id:1234abcd...`
SHIFTER_IMAGE has the resolved image id (e.g., `1234abcd...`)

addressed in PR 219

**Comment by scanon** [comment]
Closing
