### ISSUE TITLE
Option to wipe environment.

### ISSUE THREAD

**Issue by scanon** [NERSC/shifter#151]
From email list...

It would be very helpful if there was an option to Shifter to clear all the user's environment variables before starting a container. One primary use of containers is to provide different versions/stacks of packages that already exist in the native system. However, environment variables set natively (PATH, LD_LIBRARY_PATH,PYTHONHOME, etc) can cause conflicts when trying to use packages in a container...and not every image explicitly clears the environment.

We actually do this already for some variables.  A generic option that wipes everything (or an option to retain the parent environment would be good).

**Comment by dmjacobsen** [comment]
This is addressed in PR214

**Comment by dmjacobsen** [comment]
PR 214 was merged and will be in upcoming 18.03.1 release
