### ISSUE TITLE
dep/build_ssh.sh pulls a non-existent zlib version 1.2.8. zlib version 1.2.10 works

### ISSUE THREAD

**Issue by alanm-cray** [NERSC/shifter#152]
The build script dep/build_ssh.sh attempts to download a 1.2.8 version of zlib which results in a 404 file downloaded as zlib-1.2.8.tar.gz.

`opal-p1:/usr/src/packages/BUILD/shifter-16.08.3/dep # ./build_ssh.sh`
`.....snip.....`
`make[2]: Leaving directory '/usr/src/packages/BUILD/shifter-16.08.3/dep/build/libressl'`
`make[1]: Leaving directory '/usr/src/packages/BUILD/shifter-16.08.3/dep/build/libressl'`
`tar: This does not look like a tar archive`
`gzip: stdin: not in gzip format`
`tar: Child returned status 1`
`tar: Error is not recoverable: exiting now`

`opal-p1:/usr/src/packages/BUILD/shifter-16.08.3/dep # cat build/zlib-1.2.8.tar.gz`
`<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">`
`<html><head>`
`<title>404 Not Found</title>`
`</head><body>`
`<h1>Not Found</h1>`
`<p>The requested URL /zlib-1.2.8.tar.gz was not found on this server.</p>`
`<p>Additionally, a 404 Not Found`
`error was encountered while trying to use an ErrorDocument to handle the request.</p>`
`</body></html>`

The URL http://zlib.net/zlib-1.2.8.tar.gz is no longer valid. Modifying dep/build_ssh.sh to the current release of zlib results in successful completion of dep/build_ssh.sh:

`diff --git a/dep/build_ssh.sh b/dep/build_ssh.sh`
`index 40f0a55..e356e59 100755`
`--- a/dep/build_ssh.sh`
`+++ b/dep/build_ssh.sh`
`@@ -10,7 +10,7 @@ SPRT_PREFIX=$( mktemp -d )`
` PREFIX=$( mktemp -d )`
` MUSL_VERSION=1.1.8`
` LIBRESSL_VERSION=2.1.6`
`-ZLIB_VERSION=1.2.8`
`+ZLIB_VERSION=1.2.10`
` OPENSSH_VERSION=6.8p1`

**Comment by scanon** [comment]
This was resolved with PR161 as noted by Alan.
