### ISSUE TITLE
Shifter cannot pull from registry using non-standard port

### ISSUE THREAD

**Issue by cdm-work** [NERSC/shifter#156]
If you set up a private registry, the default port it uses is 5000.  However, if you leave this set and then try to use it with Shifter, the connection fails.  If the server name is 'private', then the command attempted is:
   shifterimg pull docker:private:5000/my-repo:latest

I suspect that the command fails because the ':' separating the registry from the port causes the processing of type/image/tag to break down.

While it is easy to state that a site should just change the registry configuration to use the standard port of 443, there may be valid reasons for them to need to use an alternate port, and Shifter should be able to accommodate such needs.

**Comment by scanon** [comment]
Use the url option in the location specification.

Here is a snippet from my imagemanager.json I use for local testing on my laptop.

        "local": {
            "remotetype": "dockerv2",
            "url": "http://localhost:5000",
            "authentication": "http"
        }

You can even set the DefaultImageLocation to this location so that it is used by default.

**Comment by cdm-work** [comment]
I tried this with the 16.08.3 release, and I couldn't get it to work.  The 'shifter_worker' log would report 'Connection refused'.

While not what I had, this would be the form that I used:
`"private": {
    "remotetype": "dockerv2",
    "authentication": "http",
    "url": "http://10.11.12.13:5000"
}`

I would also run 'tcpdump' on the node that I was attempting the 'shifterimg pull private/image:tag' and nothing was leaving the system using port 5000.  If I changed 'private' to be the IP address in the URL, I would then see a request go out, but it was to port 80, not 5000 as specified in the URL.

**Comment by scanon** [comment]
Maybe this was introduced after 16.08. I'll need to check. Can you do a quick grep for url in your tree.

**Comment by cdm-work** [comment]
Looking through the 'shifter-16.08' branch code, I do see:
```
    url = 'https://%s' % location
    if 'url' in params:
        url = params['url']
```
in the imagegw/shifter_imagegw/imageworker.py file.  So I would have expected it to work.  (I also find it in our central copy of the code.)  But unless I'm doing something wrong, it clearly isn't working as expected.

**Comment by scanon** [comment]
Did you restart your image worker after updating the config?  Also make sure you've killed off any old versions.

**Comment by cdm-work** [comment]
I ran `systemctl restart shifter_worker`.  I also, out of habit, restarted 'shifter_imagegw'.

**Comment by cdm-work** [comment]
I retried this and used a different filter on 'tcpdump'.  Using my 'private' location key, the query for the image was sent out, but it was sent to port 80, rather than port 5000 as was configured in the 'url' parameter.  Because the server isn't listening on port 80, it correctly considers it as 'Connection refused'.

After carefully walking through the code, I'm pretty sure the bug is in the _setup_http_conn() method in the dockerv2.py file.  Because the 'server' at this point would be '10.11.12.13:5000', it would get split into server and port.  But because the protocol is 'http', it then creates the 'conn' object with just the server; the 'port' is not passed into 'httplib.HTTPConnection()'.  This is why it ends up using port 80 even though 5000 was specified.

You may want to just move the `if ':' in server:` check into the 'https' code processing; if the 'server' variable was left as '10.11.12.13:5000', that would be accepted by HTTPConnection(), I believe.

**Comment by cdm-work** [comment]
Please reopen this issue.
