### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by henkela** [NERSC/shifter#170]
Hi, 

when I try to build shifter on centos 7 it fails most of the times at 
./build_ssh.sh > build_ssh.log
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  883k  100  883k    0     0   133k      0  0:00:06  0:00:06 --:--:--  215k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2798k  100 2798k    0     0   299k      0  0:00:09  0:00:09 --:--:--  733k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   334  100   334    0     0     56      0  0:00:05  0:00:05 --:--:--    76
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1441k  100 1441k    0     0   177k      0  0:00:08  0:00:08 --:--:--  401k
tar: This does not look like a tar archive

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
make[2]: *** [udiRoot_dep.tar] Error 2
make[2]: Leaving directory `/root/shifter/dep'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/shifter'
make: *** [all] Error 2

In your CI, I saw that it's working on ubuntu. Should it work on Centos7 as well? 

thanks for any hints.

**Comment by BigV72** [comment]
Hello, did you ever figured it out? I am having the same issue on Ubuntu.

**Comment by scanon** [comment]
Sorry, I had overlooked this issue before.

I think there is a broken URL.  This is fixed in the dev branch.  If you are feeling adventurous, you can try this out.  Otherwise you can look at this change shown here...

https://github.com/NERSC/shifter/commit/d05138d879f406d1ed0fea911f21719d7702407a#diff-16bfcf0d9f21f80643dd8669ca3ad882

**Comment by dmjacobsen** [comment]
This is now corrected in the master and shifter-18.03 branches.
