### ISSUE TITLE
HTTP 400 when pulling images

### ISSUE THREAD

**Issue by ynop** [NERSC/shifter#232]
Hi

When i try to pull some images i get a HTTP 400 error in the logs. It doesn't show up with every image.

As far as i could reproduce it only shows up when the layer pull request responds with a location header to download the layer from.

https://github.com/NERSC/shifter/blob/032275bbd567cd9a140ec1b50262d78ff2648c85/imagegw/shifter_imagegw/dockerv2.py#L539-L545

Now the request to the new location fails. It works when I replace the `self.headers` with `{}` (if there was a location response) in:
https://github.com/NERSC/shifter/blob/032275bbd567cd9a140ec1b50262d78ff2648c85/imagegw/shifter_imagegw/dockerv2.py#L529-L530

**Comment by scanon** [comment]
@ynop See this commit in my fork.

https://github.com/scanon/shifter/commit/a946e56aa1e3a9654d240acfaa681c0699e0f6e5

**Comment by scanon** [comment]
This was merged.  Closing.
