### ISSUE TITLE
deleting an image

### ISSUE THREAD

**Issue by DriftingPig** [NERSC/shifter#233]
Hi,
I have to do some debug job on my images. And I have to upload many versions of these images because of this. Is there anyway that I can delete the image I uploaded on NERSC?

**Comment by scanon** [comment]
Please file a ticket in NERSC's service now.  We use this issue tracker for the Shifter code base.  To answer your question, we currently limit deleting images to an admin function so you will need to make a request and list which images to remove.  We hope to rework this in the future so regular users can do this.
