### ISSUE TITLE
no apparent support for loop devices!FAILED to loop mount image

### ISSUE THREAD

**Issue by liuxiaopiao** [NERSC/shifter#241]
When using shifter, met the below error when starting container:
`[test@slurm-ctl18 ~]$ shifter --image=alpine
ERROR: no apparent support for loop devices!FAILED to loop mount image: /images/f33084b4b6032f9c77744a165174368fa4aed696ac301bfe504fa5533121690f.squashfs
FAILED to mount image on loop device.
FAILED to setup image.
`
Image can pull successfully and also did 
`[test@slurm-ctl18 ~]$ sudo modprobe loop
 [test@slurm-ctl18 ~]$ lsmod | grep loop
loop                   32768  0
[test@slurm-ctl18 ~]$ echo loop > /etc/modules-load.d/loop.conf
`
I have followed the step mentioned in https://github.com/NERSC/shifter/blob/master/doc/install/centos7.rst#id1 and built with Slurm support.  
Could you please help me give me some suggestions on this? Thanks a lot

**Comment by dmjacobsen** [comment]
it looks like shifter is looking for /dev/loop0

do you have /dev/loop0?

**Comment by liuxiaopiao** [comment]
Thanks @dmjacobsen a lot for helping checking this. I didn't have /dev/loop0 on this vm. 
[test@slurm-ctl18 ~]$  ls -ltr /dev/loop*
crw-rw----. 1 root disk 10, 237 Dec 18 22:00 /dev/loop-control  

Do I need to create one /dev/loop0 manually before running the shifter container?

**Comment by liuxiaopiao** [comment]
Manually created one /dev/loop0 and now it works. 

But I have installed 17.11 version rpms which are downloaded from http://portal.nersc.gov/project/bigdata/shifter/ and it works fine without manually creating /dev/loop0. 

So want to know 
1. why we need to create this manually. 
2. Is it special for shifter package with slurm support. 
3. Is it special for 18.03 version? 

@dmjacobsen , could you please give me a hand on this when you have bandwidth?   Thanks a lot.

**Comment by scanon** [comment]
This is dependent on the host system.  The loop back is used through Shifter.  So not unique to the Slurm integration.

The 18.03 has several new features and is a little easier to deploy.  I'll take an action to create some new RPMs and advertise those.

**Comment by scanon** [comment]
Closing this.
