### ISSUE TITLE
Pulling by hash

### ISSUE THREAD

**Issue by scanon** [NERSC/shifter#248]
Docker supports pulling an image by a hash (assuming the hash is still present at the registry).  We should support this in Shifter too.

e.g.
docker pull openchemistry/psi4@sha256:36b80ed11119cf568f071e4a2be1488782ac21618bfd21117b8b7f00193b386a

**Comment by dmjacobsen** [comment]
seems reasonable to me

**Comment by scanon** [comment]
Replaced by #299
