### ISSUE TITLE
ImageGW Documentation for Private Registries

### ISSUE THREAD

**Issue by PrimordialKangaroo** [NERSC/shifter#263]
Can documentation for private registry usage be fleshed out in the imagegw directory. It's currently unclear exactly how one should use syntax in the imagemanager.json along with the pull syntax to specify the alternate location in the imagemanager.json and the image, or if it supports multiple levels of image names. It is also unclear what the multiple platforms systems are used for. Lastly a more explanatory guide for using the docker-compose would be useful as the additional services in the example compose yml are not explained.

**Comment by scanon** [comment]
I'll try to review what's there and see if I can make some updates.

**Comment by scanon** [comment]
I have added a section to the docs/faq section on this.
