### ISSUE TITLE
No `starttest' target in imagegw/Makefile?

### ISSUE THREAD

**Issue by ashalper-usgs** [NERSC/shifter#274]
The README file under `imagegw` [references a `starttest' Make target](https://github.com/NERSC/shifter/tree/master/imagegw#start-gateway-with-docker-and-docker-compose), but one does not appear in the configured source for me:
```
root@hemi:~/shifter/imagegw# make starttest
make: *** No rule to make target 'starttest'.  Stop.
root@hemi:~/shifter/imagegw# 
```

**Comment by maxim-belkin** [comment]
`starttest` is defined in `Makefile.test`, so it's:

```
make -f Makefile.test starttest
```

**Comment by scanon** [comment]
Yes.  Good point.  I should add that.
