### ISSUE TITLE
Shifter not handling file removals in a layer correctly

### ISSUE THREAD

**Issue by scanon** [NERSC/shifter#55]
Docker uses a "whitelist" file to remove files and handle other special cases.  This needs to be added to the docker handler.

**Comment by dmjacobsen** [comment]
whiteouts

https://github.com/docker/docker/blob/master/pkg/archive/whiteouts.go

I created a test repo which does:
rm -rf /usr/local
then
creates a file
then
creates a hard link to that file

I find that the directory removal leads to a .wh.local file in the layer
I find that the hard link is duplicated, both in the layers and in docker.  The above link corroborates that hard link whiteouts are not persisted to layers.  stat'ing the files in docker shows that the cross-layer hardlinks do, in fact, have different inode ids with no increment on the hardlink reference count.

**Comment by dmjacobsen** [comment]
this should have been fixed in pr #59
