### ISSUE TITLE
Launching an MPI application

### ISSUE THREAD

**Issue by lichinka** [NERSC/shifter#64]
Hi,

I have packaged the OSU MPI benchmarks in a Docker image, which was then correctly imported into Shifter v20160422. For reference, the image name is `shifter-mpi:cscs.0.4` and can be found [on the Docker hub](https://hub.docker.com/r/lichinka/shifter-mpi/).
When trying to launch the Shifter container with SLURM, I get the following:

```
$> sbatch shifter.sbatch
Submitted batch job 19374
$> cat slurm-19374.out
Checking system directories ... done
Gathering required libraries ... done
This test requires exactly two processes
This test requires exactly two processes
srun: error: nid00013: task 1: Exited with exit code 1
srun: Terminating job step 19374.0
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
srun: error: nid00012: task 0: Exited with exit code 1
Cleaning up ... done
```

It seems that Shifter (or SLURM) is not recognizing the application as being MPI-enabled and is thus launching two separate and unrelated processes. In MPI words, two communicators are created containing just one process each, although the correct behavior should be one communicator containing both processes.

On the other hand, the same application works as expected if launched without Shifter. 
I tested using the same module set and SLURM batch file:

```
$> sbatch native.sbatch
Submitted batch job 19373
$> cat slurm-19373.out
Checking system directories ... done
Gathering required libraries ... done
Show quoted text
1                       0.58
2                       2.62
4                       5.20
8                      10.60
16                     21.19
32                     42.41
64                     84.70
128                   168.11
256                   330.46
512                   644.89
1024                 1012.78
2048                 1594.93
4096                 2258.28
8192                 4483.78
16384                6568.17
32768                6324.26
65536                6872.48
131072               9726.56
262144               9811.18
524288               9849.81
1048576              9869.74
2097152              9591.84
```

For reference, the container image is using MPICH 3.2 and the `cray-mpich-abi` modules are loaded before launching Shifter with `srun`.
The scripts and source code used can be found [on this repository](https://github.com/lichinka/shifter-mpi).

Thanks,
Lucas

**Comment by dmjacobsen** [comment]
Hi Lucas,

Sorry thought I had replied to this earlier but I guess I didn't click "Comment".

For the ABI method to work, which I haven't personally tried, you'll need to get Cray's libmpi.so to override the one the application is linked against in the container.

If I were setting it up at NERSC (will do shortly), I would mount /opt/cray into the images using the siteFs capability in udiRoot.conf.  Then, one would need to manipulate LD_LIBRARY_PATH using siteEnvPrepend.  I haven't worked out the detailed paths for that yet.

What does your udiRoot.conf look like?  Are you doing something else to import bits of /opt/cray into the container?

-Doug

**Comment by dmjacobsen** [comment]
Hello,

I got it to work without udiRoot.conf modifications as a test using user volume mounts and env manipulation.

```
dmj@edison01:/scratch1/scratchdirs/dmj/optcray> salloc --image=lichinka/shifter-mpi:cscs.0.4 --volume=/scratch1/scratchdirs/dmj/optcray:/opt/cray -p realtime -c 48 --exclusive -t 20 -N 2 -n 2
salloc: Granted job allocation 520499
salloc: Waiting for resource configuration
salloc: Nodes nid0[6077-6078] are ready for job
dmj@nid06077:/scratch1/scratchdirs/dmj/optcray> srun shifter /bin/bash -c "LD_LIBRARY_PATH=/opt/cray/ugni/default/lib64:/opt/cray/xpmem/default/lib64:/opt/cray/pmi/default/lib64:/opt/cray/udreg/default/lib64:/opt/cray/mpt/default/gni/mpich-gnu-abi/4.9/lib:/opt/cray/alps/default/lib64:/opt/cray/wlm_detect/default/lib64 /usr/local/libexec/osu-micro-benchmarks/mpi/pt2pt/osu_bw"
# OSU MPI Bandwidth Test v5.3
# Size      Bandwidth (MB/s)
1                       1.53
2                       3.06
4                       6.17
8                      12.35
16                     24.69
32                     49.34
64                     98.65
128                   196.31
256                   384.51
512                   746.59
1024                 1096.44
2048                 1702.93
4096                 2314.13
8192                 5132.51
16384                8487.16
32768                9094.39
65536                9537.90
131072               9744.07
262144               9852.46
524288               9906.97
1048576              9923.97
2097152              9936.35
4194304              9886.94
dmj@nid06077:/scratch1/scratchdirs/dmj/optcray> exit
salloc: Relinquishing job allocation 520499
salloc: Job allocation 520499 has been revoked.
dmj@edison01:/scratch1/scratchdirs/dmj/optcray>
```

I did this by running extra/dumpCurrentOptCray.sh from the shifter repo and extracting it into a path that was already being imported into the container (/scratch2), then using volume mounts to put it in /opt/cray.

Finally I set LD_LIBRARY_PATH as shown above -- awkward because of the way the shifter command runs.  But it does work.  Should be possible to get a number of improvements, particularly under CLE 6.0 to ensure those libraries under opt/cray are memory resident.

-Doug

**Comment by lichinka** [comment]
Thanks a lot for the step-by-step instructions.
I ran into a problem when trying to mount the libraries under `/opt/cray`:

```
$> srun shifter --image=docker:lichinka/shifter-mpi:cscs.0.4 --volume=/scratch/santis/lucasbe/cray_libs:/opt/cray /bin/bash -c "ls -l /opt"
FAILED to find user volume to: /var/udiMount//opt/cray
FAILED to setup user-requested mounts.
FAILED to setup image.
FAILED to find user volume to: /var/udiMount//opt/cray
FAILED to setup user-requested mounts.
FAILED to setup image.
srun: error: nid00012: task 0: Exited with exit code 1
srun: Terminating job step 20469.0
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
srun: error: nid00013: task 1: Exited with exit code 1
```

My Shifter version on this host is 15.12.0. Could this be the problem?

**Comment by dmjacobsen** [comment]
i suspect you have an older version of shifter that didnt attempt to auto-create mount points (only works under / or /opt at present).  try pre-creating /opt/cray directory in image, or just use `/scratch/santis/lucasbe/cray_libs` instead of `/opt/cray` in LD_LIBRARY_PATH (with no volume mount)

**Comment by lichinka** [comment]
I have reproduced the steps above without the volume mount, but now I am getting a system error when trying to launch the `osu_bw`:

```
$> srun shifter --image=docker:lichinka/shifter-mpi:cscs.0.4 /bin/bash -c "LD_LIBRARY_PATH=/scratch/santis/lucasbe/cray_libs /usr/local/libexec/osu-micro-benchmarks/mpi/pt2pt/osu_bw"
Mon Jun 13 07:48:27 2016: [unset]:_pmi_alps_init:alps_get_placement_info returned with error -1
Mon Jun 13 07:48:27 2016: [unset]:_pmi_init:_pmi_alps_init returned -1
Mon Jun 13 07:48:27 2016: [unset]:_pmi_alps_init:alps_get_placement_info returned with error -1
Mon Jun 13 07:48:27 2016: [unset]:_pmi_init:_pmi_alps_init returned -1
[Mon Jun 13 07:48:27 2016] [c0-0c0s6n2] Fatal error in MPI_Init: Other MPI error, error stack:
MPIR_Init_thread(525): 
MPID_Init(225).......: channel initialization failed
MPID_Init(598).......:  PMI2 init failed: 1 
[Mon Jun 13 07:48:27 2016] [c0-0c0s6n3] Fatal error in MPI_Init: Other MPI error, error stack:
MPIR_Init_thread(525): 
MPID_Init(225).......: channel initialization failed
MPID_Init(598).......:  PMI2 init failed: 1 
srun: error: nid00026: task 0: Aborted
srun: Terminating job step 350960.5
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
srun: error: nid00027: task 1: Aborted
```

The same error appears whether I use the `cray-mpich` or the `cray-mpich-abi` modules.
Does the error message look familiar to you?

**Comment by dmjacobsen** [comment]
Hi Lucas,

I suspect the issue is that the LD_LIBRARY_PATH you are setting is not complete.  Presuming you extracted the optcray archive in /scratch/santis/lucasbe/cray_libs, you would need to replace every occurence of "/opt/cray" in the following string with "/scratch/santis/lucasbe/cray_libs":

/opt/cray/ugni/default/lib64:/opt/cray/xpmem/default/lib64:/opt/cray/pmi/default/lib64:/opt/cray/udreg/default/lib64:/opt/cray/mpt/default/gni/mpich-gnu-abi/4.9/lib:/opt/cray/alps/default/lib64:/opt/cray/wlm_detect/default/lib64

Note that modules loaded in the external environment will have little effect on the operation of the process within the container (since LD_LIBRARY_PATH is unset when shifter starts).

-Doug

**Comment by lichinka** [comment]
Hi Doug,

We solved this issue by exposing the 'cray_libs' to the deployed container when Shifter starts and setting LD_LIBRARY_PATH accordingly. 
This also speeds deployment up since there is no need to do the dynamic gathering of the libraries.
Big thanks to you and Miguel for solving this one.

Cheers,
Lucas
