### ISSUE TITLE
Non-ascii characters in tar file names cause an exception

### ISSUE THREAD

**Issue by scanon** [NERSC/shifter#68]
The error occurs in the os.path.join.

**Comment by dmjacobsen** [comment]
Do you happen to have the exception stack trace?

**Comment by dmjacobsen** [comment]
Is there a particular image that provokes this?  A simple test-case with an UTF-8 character doesn't seem to have the problem in python 2.6

```
dmj@edison11:~> cat testpath.py
#!/usr/bin/python

import os
import sys

for (dirpath, dirnames, fnames) in os.walk(sys.argv[1]):
    for fname in fnames:
        print os.path.join(dirpath, fname)
dmj@edison11:~> python testpath.py testpath
testpath/asdfäasdf
dmj@edison11:~>
```

**Comment by dmjacobsen** [comment]
I think I'm beginning what the problem _might_ be.  It seems that `tar tf <tarfile>` escapes the multibyte unicode characters

```
dmj@edison01:~> tar tf testpath.tar
testpath/
testpath/asdf\303\244asdf
dmj@edison01:~>
```

I'm trying to see if explicitly re-encoding the output of `tar tf` as unicode will reconstruct the string correctly.

**Comment by dmjacobsen** [comment]
I have just pushed https://github.com/NERSC/shifter/tree/fixtar the fixtar branch

this has not been tested much at all yet, but it basically throws away the old approach to extracting layers and relies instead upon python's tarfile, which is pax capable and explicitly exposes that functionality (meaning utf-8 compatible among other things).

i took the opportunity to fully examine the files to be extracted in all layers and compute a minimal set of files to extract by comparing the paths in the tables of contents ahead of time, filtering possibly dangerous content, and then extract just that minimal set.

this reduces the amount of disk thashing by, if it is coded correctly, only extracting the final versions of files and never extracting files which would be removed by a whiteout or replaced in a subsequent layer.

I did some very light testing with the builtin main fxn on the dockerv2 module, but don't have time right now (owing to cori) to test extensively.  I was able to successfully extract both ubuntu and tensorflow with this code.

Shane and Miguel, I'd appreciate it if you could please test this functionality.

Thanks,
Doug

**Comment by dmjacobsen** [comment]
I think this has been resolved in the tarfile modifications. I know that Miguel needed to make some further configuration settings to get certain cases working, but if possible I'd like to understand that better.

**Comment by dmjacobsen** [comment]
Looks like this also requires fixes suggested by Miguel.  I've added a sitecustomize.py as he described and updated the documentation to point out that it needs to be in the celery worker's PYTHONPATH.

I think this should be mostly fixed now.  There may still be some deployment updates (e.g., with the docker imagegw/worker stuff that needs to be fixed).
