### ISSUE TITLE
Shifter ignoring image configured PATH when executing binary

### ISSUE THREAD

**Issue by cdm-work** [NERSC/shifter#77]
I created an image which installed binaries in a directory that is not part of the standard path, so the Dockerfile includes an 'ENV' statement to add the install directory to the path.  If the built image is used with Docker, I can simply provide the binary name without a full path and it runs.

If I use the same image with shifter, the command fails as if the binary cannot be found.  But if I supply the full path, then it works.  And 'printenv' from within the environment shows that the PATH includes the install directory.  So this seems to represent a regression from Docker behavior.

**Comment by dmjacobsen** [comment]
I think this is solved in the searchPath branch.  Will do some additional testing to validate.

**Comment by dmjacobsen** [comment]
PR #81 fixes this, and is now merged.
