### ISSUE TITLE
shifter raising error when both SHIFTER_VOLUME and '--volume' used

### ISSUE THREAD

**Issue by cdm-work** [NERSC/shifter#86]
Based on SHIFTER/--image handling, we would expect that if both SHIFTER_VOLUME and '--volume' are used, that shifter would ignore the SHIFTER_VOLUME environment variable.  However, shifter currently raises an error.

In my testing, this is the error that is returned:
[[ERROR]]
Unknown flag:
Invalid mount flags specified: /data
Failed to parse volume map options
[[/ERROR]]
('/data' was a destination mount in both the variable and option specification.)

**Comment by dmjacobsen** [comment]
Hello,

I think this I fixed this today in PR #87.

Thanks for reporting the issue!
-Doug
