### ISSUE TITLE
allowedImageTypes doesn't seem to work

### ISSUE THREAD

**Issue by chrissamuel** [NERSC/shifter#93]
The default settings for allowedImageTypes doesn't seem to work on RHEL6:

> allowedImageTypes=docker custom

results in:

> [samuel@bruce ~]$ shifter
> Couldn't understand key: allowedImageTypes
> FAILED to parse udiRoot configuration.

The same error happens with only one of either `docker` or `custom`.

Commenting that line out completely seems to resolve it and looking at `extra/cle6/ansible/roles/shifter/templates/udiRoot.conf.j2` instead shows that whilst the comments are present the line itself is absent, instead having:

> perNodeCachePath={{shifterPerNodeCachePath}}

in its place.

**Comment by dmjacobsen** [comment]
This was a vestigial bit in the example -- thanks for pointing it out.  I've removed it entirely in PR#98.  I think this should fix the issue, sorry for the trouble.
