### ISSUE TITLE
Shifter appears to rely on mkfs.xfs which is not available in RHEL6

### ISSUE THREAD

**Issue by chrissamuel** [NERSC/shifter#94]
The `udiRoot.conf` file has (in our RPM builds):

> mkfsXfsPath=NotFound

as RHEL6 does not provide a mkfs.xfs binary (it wasn't in the stock distro until RHEL7).

There doesn't appear to be a good way to avoid it as commenting it out results in:

> [samuel@bruce ~]$ shifter
> "mkfsXfsPath" is not defined
> FAILED to parse udiRoot configuration.

All I've been able to do now to get past this is to set that to `/bin/false`, but that's likely to be sub-optimal.

Any chance of making the filesystem used configurable please?

thanks!
Chris

**Comment by dmjacobsen** [comment]
This field really shouldn't be required, it's only needed for the per-node cache stuff, which is an exciting capability for diskless systems, but is not required for shifter to run.  I'll update the code to not require mkfsXfsPath to be required.

**Comment by chrissamuel** [comment]
Thanks for that Doug!

All our compute nodes are diskless too so this feature might be useful to us as well, just with ext4 rather than XFS. :-)

All the best,
Chris

**Comment by dmjacobsen** [comment]
I've removed the hard requirement that mkfsXfsPath is defined in  PR#98 and PR#99.  I think this should resolve this issue, please open a new one if you are still seeing trouble.
