### ISSUE TITLE
Support RPM %{dist} syntax in spec file

### ISSUE THREAD

**Issue by chrissamuel** [NERSC/shifter#95]
Currently the spec file has just:

`Release:  1`

This means that it ignores whatever is passed through by RPM via the --dist option, and supporting %{dist} is a requirement for Fedora (for instance).

The fix is trivial:

`Release:  1%{?dist}`

This makes it trivial to build RPMs with newer dist numbers and so be able to yum upgrade them, for instance my git build-rpm does:

`git build-rpm  --define with_slurm=/usr/local/slurm/latest --spec-file shifter.spec --dist ".$(date +%Y%m%d.%H%M)"`

Fedora info: https://fedoraproject.org/wiki/Packaging:DistTag

All the best!
Chris

**Comment by dmjacobsen** [comment]
This was fixed in PR#109, and I just tested it.
